
version 2.1

ALTER TABLE AuditURL ADD COLUMN ClipPath TEXT;
ALTER TABLE AuditURL ADD COLUMN ClipHTML TEXT;

ALTER TABLE URL ADD COLUMN ClipPath TEXT;
ALTER TABLE URL ADD COLUMN ClipHTML TEXT;

/////

version 2.2 - Changes made 30/09/10

// New TABLES
CREATE TABLE `Search` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  `SearchID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  `UserID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  `Name` varchar(254) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  `CreationDate` double NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  `ModificationDate` double NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  `Scope` varchar(3) NOT NULL default 'my',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  `Depth` int(11) default '1',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  `FocalNode` varchar(50) default NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  `LinkTypes` text,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  `LinkGroup` varchar(50) default NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  `LinkSet` varchar(50) default NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  `Direction` int(1) default '2',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  `LabelMatch` int(1) default '0',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  PRIMARY KEY  (`SearchID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  KEY `Search_ibfk_1` (`UserID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  KEY `Search_ibfk_2` (`FocalNode`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  CONSTRAINT `Search_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  CONSTRAINT `Search_ibfk_2` FOREIGN KEY (`FocalNode`) REFERENCES `node` (`NodeID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;
        
CREATE TABLE `SearchAgent` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   `AgentID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
   `UserID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
   `SearchID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
   `CreationDate` double NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
   `ModificationDate` double NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
   `LastRun` double default '0',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
   `Email` int(1) NOT NULL default '0',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
   `RunInterval` varchar(50) NOT NULL default 'monthly',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
   PRIMARY KEY  (`AgentID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   KEY `SearchAgent_ibfk_1` (`UserID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
   KEY `SearchAgent_ibfk_2` (`SearchID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
   CONSTRAINT `SearchAgent_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
   CONSTRAINT `SearchAgent_ibfk_2` FOREIGN KEY (`SearchID`) REFERENCES `search` (`SearchID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 ) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;
     
CREATE TABLE `SearchAgentRun` (                                                                                                                                                                                                                                                                                                                                                                     
  `RunID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                     
  `AgentID` varchar(50) default NULL,                                                                                                                                                                                                                                                                                                                                                               
  `UserID` varchar(50) default NULL,                                                                                                                                                                                                                                                                                                                                                                                                     
  `From` double default NULL,                                                                                                                                                                                                                                                                                                                                                                       
  `To` double default NULL,                                                                                                                                                                                                                                                                                                                                                                         
  `Type` varchar(255) default NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                          
  PRIMARY KEY  (`RunID`),                                                                                                                                                                                                                                                                                                                                                                           
  KEY `AgentID` (`AgentID`),                                                                                                                                                                                                                                                                                                                                                                        
  CONSTRAINT `SearchAgentRun_ibfk_1` FOREIGN KEY (`AgentID`) REFERENCES `searchagent` (`AgentID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                 
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC   

CREATE TABLE `SearchAgentRunResults` (                                                                                                                                                                                                                                                                                            
  `RunID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                   
  `TripleID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                
   PRIMARY KEY  (`RunID`,`TripleID`),                                                                                                                                                                                                                                                                                              
  CONSTRAINT `SearchAgentRunResults_ibfk_1` FOREIGN KEY (`RunID`) REFERENCES `SearchAgentRun` (`RunID`) ON DELETE CASCADE                                                                                                                                                                                                         
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `URLGroup` ( 
`URLID` varchar(50) NOT NULL default '', 
`GroupID` varchar(50) NOT NULL default '', 
`CreationDate` double NOT NULL default '0',                                                                
PRIMARY KEY  (`URLID`,`GroupID`),  
KEY `GroupID` (`GroupID`), 
CONSTRAINT `urlgroup_ibfk_1` FOREIGN KEY (`URLID`) REFERENCES `URL` (`URLID`) ON DELETE CASCADE,               	
CONSTRAINT `urlgroup_ibfk_2` FOREIGN KEY (`GroupID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE              
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC    

//TO DO - Complete actual sql update statements

// Node table has a new foreign key contraint on UserID + new Index on UserID
//   KEY `UserID` (`UserID`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
//   CONSTRAINT `Node_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

// URL table has a new foreign key contraint on UserID + new Index on UserID
//   KEY `UserID` (`UserID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
//   CONSTRAINT `URL_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

// TripleGroup is now InnoDB and has foreign key constraints on TripleID and GroupID +  Index on GroupID
//   KEY `GroupID` (`GroupID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
//   CONSTRAINT `TripleGroup_ibfk_2` FOREIGN KEY (`GroupID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                                                  
//   CONSTRAINT `TripleGroup_ibfk_1` FOREIGN KEY (`TripleID`) REFERENCES `Triple` (`TripleID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                               
// ) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

// NodeGroup is now InnoBD and has foreign key constraints on NodeID and GroupID + Index on GroupID
//    KEY `GroupID` (`GroupID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
//    CONSTRAINT `NodeGroup_ibfk_2` FOREIGN KEY (`GroupID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                         
//    CONSTRAINT `NodeGroup_ibfk_1` FOREIGN KEY (`NodeID`) REFERENCES `Node` (`NodeID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                            
//  ) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC                                                                                                                                                                                                                                                                                                                                                                                                                                        

// UserGroup is now InnoBD and has foreign key constraints on UserID and GroupID + Index on UserID
//    KEY `UserID` (`UserID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
//    CONSTRAINT `UserGroup_ibfk_2` FOREIGN KEY (`GroupID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                                                                                   
//    CONSTRAINT `UserGroup_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                     
//  ) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

// UserCache is now InnoBD; IdeaID now NodeID varchar 50 and has foreign key constraints on UserID and NodeID + Index on NodeID
//    `NodeID` varchar(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
//     KEY `NodeID` (`NodeID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
//     CONSTRAINT `UsersCache_ibfk_2` FOREIGN KEY (`NodeID`) REFERENCES `Node` (`NodeID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
//     CONSTRAINT `UsersCache_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
// ) ENGINE=InnoDB AUTO_INCREMENT=378 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

// log table is now InnoDB and has foreign key constraint on UserID + Index on UserID
//   KEY `UserID` (`UserID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
//   CONSTRAINT `Log_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
//) ENGINE=InnoDB AUTO_INCREMENT=13950 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

//  URL Table        `Private` enum('Y','N') NOT NULL default 'Y',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

